In [1]:
import pandas as pd

# Create first DataFrame (Employees)
df1 = pd.DataFrame({
    'employee_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David']
})

# Create second DataFrame (Departments)
df2 = pd.DataFrame({
    'employee_id': [3, 4, 5, 6],
    'department': ['Engineering', 'Marketing', 'Sales', 'HR']
})

# Perform the inner join
result = pd.merge(df1, df2, on='employee_id', how='inner')

result

   employee_id     name   department
0            3  Charlie  Engineering
1            4    David    Marketing

In [14]:
from helper_functions import *
from sklearn.model_selection import train_test_split

study_ids = os.listdir("train_series")

train_df = pd.read_csv("train.csv").drop(columns=["Report"]).dropna()
train_series_df = pd.read_csv("train_series.csv")

train_df = train_df[train_df["StudyInstanceUID"].isin(study_ids)]
train_series_df = train_series_df[train_series_df["StudyInstanceUID"].isin(study_ids)]
full_df = pd.merge(train_df, train_series_df, on='StudyInstanceUID', how='inner')

train_ids, test_ids = train_test_split(train_df["StudyInstanceUID"], test_size=0.2, random_state=42)
train_full = full_df[full_df["StudyInstanceUID"].isin(train_ids)]
test_full = full_df[full_df["StudyInstanceUID"].isin(test_ids)]
type(train_ids)

pandas.Series

In [15]:
len(train_ids), len(test_ids)

(22, 6)

In [18]:
train_full.shape, test_full.shape

((133, 17), (33, 17))

In [17]:
full_df

,StudyInstanceUID,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture,SeriesInstanceUID,Fluid_Sensitive,Fat_Suppression,Anatomical_Plane
0,1.2.826.0.1.3680043.8.498.10095687747295410396...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.2.826.0.1.3680043.8.498.10791858932231443712...,0,0,Sagittal
1,1.2.826.0.1.3680043.8.498.10095687747295410396...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.2.826.0.1.3680043.8.498.12451507871565834868...,0,0,Coronal
2,1.2.826.0.1.3680043.8.498.10095687747295410396...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.2.826.0.1.3680043.8.498.21497837050858589852...,1,1,Coronal
3,1.2.826.0.1.3680043.8.498.10095687747295410396...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.2.826.0.1.3680043.8.498.37372672584387115708...,1,1,Sagittal
4,1.2.826.0.1.3680043.8.498.10095687747295410396...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.2.826.0.1.3680043.8.498.67495435033389756963...,1,1,Axial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,1.2.826.0.1.3680043.8.498.30246079718471552972...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.2.826.0.1.3680043.8.498.10125030789765676430...,1,1,Coronal
162,1.2.826.0.1.3680043.8.498.30246079718471552972...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.2.826.0.1.3680043.8.498.12908352013592575797...,1,1,Axial
163,1.2.826.0.1.3680043.8.498.30246079718471552972...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.2.826.0.1.3680043.8.498.13364655615747190896...,0,0,Sagittal
164,1.2.826.0.1.3680043.8.498.30246079718471552972...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.2.826.0.1.3680043.8.498.73098240504448530683...,1,1,Sagittal
165,1.2.826.0.1.3680043.8.498.30246079718471552972...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.2.826.0.1.3680043.8.498.75078392068446053207...,0,0,Coronal

In [24]:
target_columns = train_df.columns.copy().drop("StudyInstanceUID")
target_columns

Index(['ACL', 'MCL', 'Medial Meniscus', 'Lateral Meniscus', 'Medial OA',
       'Lateral OA', 'PF OA', 'Effusion', 'Synovitis', 'Baker's', 'Contusion',
       'Fracture'],
      dtype='str')

In [25]:
train_df.columns

Index(['StudyInstanceUID', 'ACL', 'MCL', 'Medial Meniscus', 'Lateral Meniscus',
       'Medial OA', 'Lateral OA', 'PF OA', 'Effusion', 'Synovitis', 'Baker's',
       'Contusion', 'Fracture'],
      dtype='str')

In [27]:
full_df[target_columns]

,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
161,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
162,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
163,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
164,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
165,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0

In [4]:
4698.00 + 1754.85 + 2388.15 - 6598.35

2242.6499999999996